folio-org/pipelines-shared-library

pipelines/rancher/project.groovy
terraform/rancher/cluster/monitoring.tf
terraform/rancher/project/postgresql.tf

Reverts folio-org/pipelines-shared-library#139

Revert "Rancher 219"

---

pipelines/rancher/cluster.groovy
vars/terraform.groovy

Rancher 647 Destroy Cluster bug fix

---

pipelines/rancher/project.groovy
src/org/folio/Constants.groovy
vars/jobsParameters.groovy

Setup Rancher for new development team - NLA

Rancher 668

---

terraform/shared/opensearch/data.tf
terraform/shared/opensearch/opensearch.tf
terraform/shared/opensearch/provider.tf
terraform/shared/opensearch/resources/es-access-policies.tpl
terraform/shared/opensearch/terraform.tf
terraform/shared/opensearch/variables.tf
terraform/shared/opensearch/versions.tf

Create terraform code for create AWS OpenSearch

Create shared opensearch

---

pipelines/automation/ecr-cleanup-images.groovy

To let the job not to be run on the master

RANCHER-655 fix agent label

---

pipelines/rancher/cluster.groovy
pipelines/rancher/project.groovy
src/org/folio/Constants.groovy
terraform/rancher/project/data.tf
terraform/rancher/project/elasticsearch.tf
terraform/rancher/project/kafka.tf
terraform/rancher/project/secrets.tf
terraform/rancher/project/variables.tf
terraform/shared/opensearch/data.tf
terraform/shared/opensearch/opensearch.tf

Fixed several error that I got when tried to run tmp cluster
Removed AWS ES and MSK from project and added data on for them 
Change password policy for shared OpenSearch because when we try run it in project we can get errors sometimes

Modify project with shared Opensearch and MSK

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
src/org/folio/models/Modules.groovy
src/org/folio/models/OkapiTenant.groovy
src/org/folio/models/RancherNamespace.groovy
vars/uiBuild.groovy

RANCHER-890 [TEMP] Include consortia related modules to consortium mode deployment

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
src/org/folio/rest_v2/Main.groovy

Create additional service admin user for rancher envs

Rancher 887

---

src/org/folio/rest_v2/Consortia.groovy

RANCHER-893

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/manageSecrets/Jenkinsfile
vars/jobsParameters.groovy
vars/kubectl.groovy

Refactor code according to comments

Rancher-834

---

src/org/folio/rest_v2/Main.groovy

All tests passed successfully, simulate procedure works as expected.

RANCHER-869 Final test v12

---

pipelines/tests/karate/karateTestsScheduledPipeline.groovy
vars/karateFlow.groovy

RANCHER-939 revert to primary LBR and enable cron expression.

Rancher-939

---

pipelines/tests/cypress/cypressTestsScheduledPipeline.groovy

Rancher 923

---

resources/edge/config.yaml
src/org/folio/rest_v2/Edge.groovy

New PR for adding requested permissions to test-user.

Rancher-928

---

src/org/folio/rest_v2/Permissions.groovy

Simple function to add missing permissions to admin user(s).

RANCHER-895 Missing permissions add function.

---

pipelines/tests/karate/karateTestsScheduledPipeline.groovy

Minor changes into scheduled karate tests pipeline + R\W split option disabled.

Rancher-966

---

vars/awscli.groovy
vars/folioTerraform.groovy

Simple fix for TF timeouts issue.

RANCHER-954 add: export TF_REGISTRY_CLIENT_TIMEOUT=20 to env variable.

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

RANCHER-970 config files adjusted.

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

RANCHER-970 config files adjusted to master branch.

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

According to response from dev team there should be 2 paths specified.

RANCHER-970 edge-fqm paths corrected.

---

pipelines/automation/start-stop-project.groovy

At 07:30 on every day-of-week from Tuesday through Friday.” UTC STOP.  > CANBERA TIME 5.30PM Evening
“At 22:30 on every day-of-week from Tuesday through Friday.”  UTC START. > CANBERA TIME 8:30 AM Morning

Rancher 1014

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespace/Jenkinsfile
src/org/folio/Constants.groovy

Rancher 969

---

pipelines/automation/start-stop-project.groovy

Start Stop
Please Check Cron time

add start stop cron

---

src/org/folio/models/OkapiUser.groovy
src/org/folio/rest_v2/Users.groovy
vars/folioDefault.groovy

https://issues.folio.org/browse/RANCHER-1016
add type = staff.  property for the adminOkapiuser's
consortium_admin, university_admin, college_admin

add type staff propery for the admin users

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/managePods/Jenkinsfile
resources/edge/ephemeral-properties.tpl
src/org/folio/rest_v2/Edge.groovy
vars/folioEdge.groovy

All related information and steps history in https://issues.folio.org/browse/RANCHER-984
NOTICE: Please keep in mind that this is a temporary solution and additional logic implementation might be required.

RANCHER-984 temp solution

---

pipelines/folioRancher/folioScheduledTesting/runNightlyCypressTests/Jenkinsfile
pipelines/folioRancher/folioTestingTools/runCypressTests/Jenkinsfile
vars/folioCypressFlow.groovy

https://issues.folio.org/browse/RANCHER-997

RANCHER-997 Modify automation pipelines to use cypress-cloud

---

vars/jobsParameters.groovy

add corsair ns name to the env list

add corsair name to environment list

---

pipelines/folioRancher/folioQualityGates/Jenkinsfile

scheleton of multiple jobs
this is sample simple template, please comment if need some additional

Rancher 1000

---

pipelines/automation/jira-tickers-move.groovy

Poppy release include.

---

pipelines/folioRancher/folioScheduledTesting/runNightlyCypressBugfestTests/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/runNightlyCypressTests/Jenkinsfile

add bugfest job. my branch is for tetsing purpose in shared library, after confirm i will change to 741
and disable cypress job cron
JIra TIcket: https://issues.folio.org/browse/RANCHER-1052
testsTimeout            : '10',  increased from 6 to 10 discussed with ostap
jenkins job : https://jenkins-aws.indexdata.com/job/folioRancher/job/folioScheduledTesting/job/runNightlyCypressBugfestTests/

add bugfest job

---

pipelines/folioRancher/folioQualityGates/Jenkinsfile
src/org/folio/Constants.groovy
vars/awscli.groovy
vars/folioHashCommitCheck.groovy

folioCIQualityGate Job
Compare Commit Hash 
Previous Commit ~Hash Saved TO AWS SSM   
https://issues.folio.org/browse/RANCHER-999
https://jenkins-aws.indexdata.com/job/folioRancher/job/folioQualityGates/job/folioCiQualityGates-RANCHER-1000/73/

Rancher 999

---

pipelines/folioRancher/folioScheduledTesting/runNightlyCypressBugfestTests/Jenkinsfile

temporary disable cron

---

pipelines/folioRancher/folioScheduledTesting/runNightlyCypressBugfestTests/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/runNightlyCypressTests/Jenkinsfile
pipelines/folioRancher/folioTestingTools/runCypressTests/Jenkinsfile

increase number of workers in cypress tests

increase number of workers in cypress tests

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
src/org/folio/Constants.groovy
terraform/rancher/project/variables.tf
vars/folioParameters.groovy

Add PostgreSQL version choice parameter

Rancher 1084

---

pipelines/folioRancher/folioDevTools/tenantManagement/createConsortia/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromRdsSnapshot/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/deleteNamespace/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/karateTestsScheduledPipeline.groovy
resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

Jira https://issues.folio.org/browse/RANCHER-1139
Additionally RW_SPLIT set to false by default

RANCHER-1139 Add module mod-batch-print to rancher

---

pipelines/folioRancher/folioDevTools/moduleDeployment/deployModulesFromJson/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromRdsSnapshot/Jenkinsfile
resources/system-users.json
src/org/folio/Constants.groovy
src/org/folio/models/Modules.groovy
src/org/folio/models/RancherNamespace.groovy
src/org/folio/rest_v2/Authorization.groovy
src/org/folio/rest_v2/Common.groovy
src/org/folio/rest_v2/Main.groovy
src/org/folio/rest_v2/Okapi.groovy
src/org/folio/rest_v2/Permissions.groovy
vars/folioDefault.groovy
vars/folioDeployFlow.groovy
vars/folioEdge.groovy
vars/folioHelm.groovy
vars/folioParameters.groovy
vars/folioVersions.groovy

Jira: https://issues.folio.org/browse/RANCHER-739

RANCHER-739 Reconfigure Jenkins jobs related to the process of update of the modules.

---

pipelines/folioRancher/folioDevTools/tenantManagement/createTenant/Jenkinsfile
vars/folioParameters.groovy

Rancher 837

---

pipelines/Jenkinsfile.template
pipelines/folioRancher/folioDevTools/moduleDeployment/deployModulesFromJson/Jenkinsfile
pipelines/folioRancher/folioDevTools/userManagement/resetSystemUserPassword/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespace/Jenkinsfile
src/org/folio/Constants.groovy
src/org/folio/models/InstallRequestParams.groovy
src/org/folio/models/RancherNamespace.groovy
src/org/folio/rest_v2/Users.groovy
terraform/rancher/project/secrets.tf
vars/folioDefault.groovy
vars/folioDeployFlow.groovy
vars/folioHelm.groovy

https://issues.folio.org/browse/RANCHER-1182

RANCHER-1182 Fix deployModulesFromJson job to use new folio-helm charts

---

src/org/folio/Constants.groovy

Updated URLs + JenkinsNotification credentials were updated in secretStore of Jenkins:

RANCHER-1213 URLs update

---

pipelines/folioRancher/folioDevTools/tenantManagement/unlockSuperTenant/Jenkinsfile

Description: Create the unlockSuperTenant job for the tenantManagement group according to the proposed structure. Implement necessary business logic in each job.
Acceptance Criteria: tenantManagement job group is created and includes unlockSuperTenant job. Job function as expected and pass their respective tests.

Rancher 1156 - Create unlockSuperTenant job for tenantManagement group

---

pipelines/folioRancher/folioTestingTools/runCypressTests/Jenkinsfile

https://folio-org.atlassian.net/browse/RANCHER-1240
Please CHECK SEVERAL TIMES these changes that have been made!!!

RANCHER-1240 Remove limitation for runCypressTests pipeline on weekends

---

src/org/folio/Constants.groovy

RANCHER-1292 orchid env into ns list

---

src/org/folio/Constants.groovy

[RANCHER-1327: Upgrade EKS on Rancher to v1.27](https://folio-org.atlassian.net/browse/RANCHER-1327)

RANCHER-1327: Upgrade EKS on Rancher to v1.27

---

pipelines/folioRancher/folioDevTools/tenantManagement/deleteTenant/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/managePods/Jenkinsfile

Minor changes into 2 pipelines. Please review and approve.

.RANCHER-1438 adjusting cron schedule by including all NSs into table.

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespace/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/deleteNamespace/Jenkinsfile
pipelines/folioRancher/folioQualityGates/Jenkinsfile
terraform/rancher/project/kafka.tf
terraform/rancher/project/locals.tf
terraform/rancher/project/main.tf
terraform/rancher/project/minio.tf
terraform/rancher/project/opensearch.tf
terraform/rancher/project/postgresql.tf
terraform/rancher/project/provider.tf
terraform/rancher/project/variables.tf
terraform/rancher/project/versions.tf

JIRA: https://folio-org.atlassian.net/browse/RANCHER-1258

[QG Part 4] RANCHER-1258 Terraform namespace provisioning fails when several ns created in parallel with Connection timeout error

---

pipelines/folioRancher/folioDevTools/moduleDeployment/deployModulesFromJson/Jenkinsfile
vars/folioHelm.groovy

Cosmetic changes to make all things alignment with DI_Slicing enabled across all deploys + remove of unsed lines of configs.

.DI_Slicing_By_Default_Everywhere

---

src/org/folio/Constants.groovy

Related Jira Ticket:
[RANCHER-1465:  Setup rancher for Leipzig team](https://folio-org.atlassian.net/browse/RANCHER-1465)

RANCHER-1465:  Setup rancher for Leipzig team

---

src/org/folio/rest_v2/Main.groovy
src/org/folio/rest_v2/Okapi.groovy

Reverts folio-org/pipelines-shared-library#508

Revert "RANCHER-1467: run re-index on MARC Authority Data"

---

pipelines/folioRancher/folioEureka/Jenkinsfile
pipelines/folioRancher/folioEureka/keycloak/Jenkinsfile
pipelines/folioRancher/folioEureka/kong/Jenkinsfile
pipelines/folioRancher/folioEureka/sidecar/Jenkinsfile
vars/common.groovy

All testing was completed in: https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/keycloak-image-draft/
Successful build results(keycloak): https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/keycloak-image-draft/19/console
(kong)https://jenkins-aws.indexdata.com/view/KitFox/job/folioRancher/job/tmpFolderForDraftPipelines/job/kong-image-draft/8/console
kong:
sidecar:
https://jenkins-aws.indexdata.com/view/KitFox/job/folioRancher/job/tmpFolderForDraftPipelines/job/sidecar-image-draft/2/console

[RANCHER-1337, RANCHER-1338, RANCHER-1339, RANCHER-1479]  | keycloak, kong, sidecar custom images build pipelines

---

pipelines/folioRancher/folioDevTools/moduleDeployment/deployModuleFromFeatureBranch/Jenkinsfile
src/org/folio/models/FolioModule.groovy
src/org/folio/rest_v2/Main.groovy
vars/folioDeployFlow.groovy
vars/folioHashCommitCheck.groovy
vars/folioNamespaceCreate.groovy
vars/folioParameters.groovy
vars/folioStringScripts.groovy

RANCHER-836 Create moduleDeployment Job Group

RANCHER-836 Create moduleDeployment Job Group

---

pipelines/Jenkinsfile.template
pipelines/folioRancher/folioDevTools/moduleDeployment/deployModulesFromJson/Jenkinsfile
pipelines/folioRancher/folioDevTools/tenantManagement/createConsortia/Jenkinsfile
pipelines/folioRancher/folioDevTools/tenantManagement/createTenant/Jenkinsfile
pipelines/folioRancher/folioDevTools/uiManagement/deployUI/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromRdsSnapshot/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/runNightlyKarateTests/Jenkinsfile
pipelines/folioRancher/folioTestingTools/folioDataMigrationExecutionTime/Jenkinsfile
pipelines/folioRancher/folioTestingTools/runKarateTests/Jenkinsfile
vars/folioKarateFlow.groovy
vars/kubectl.groovy

JIRA: https://folio-org.atlassian.net/browse/RANCHER-812

RANCHER-812 Switch Nightly Karate tests pipeline to new folioKarateFlow

---

pipelines/folioRancher/folioScheduledTesting/runNightlyCypressTests/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/runNightlyKarateTests/Jenkinsfile
src/org/folio/models/parameters/CypressTestsParameters.groovy
vars/folioKarateFlow.groovy
vars/folioTools.groovy
vars/folioTriggerJob.groovy

JIRA: https://folio-org.atlassian.net/browse/RANCHER-1521

RANCHER-1521 runNightlyCypressTests pipeline fails on stage of env provisioning

---

resources/helm/development.yaml
resources/helm/testing.yaml
src/org/folio/Constants.groovy
src/org/folio/models/RancherNamespace.groovy
terraform/rancher/project/postgresql.tf
vars/folioHelm.groovy
vars/folioNamespaceCreate.groovy

JIRA: https://folio-org.atlassian.net/browse/RANCHER-1520

RANCHER-1520 Helm values feature-switchers not work properly

---

pipelines/folioRancher/folioQualityGates/Jenkinsfile
src/org/folio/slack/SlackBuildResultRenderer.groovy
src/org/folio/slack/templates/SlackBuildResultTemplates.groovy
vars/folioSlackNotificationUtils.groovy

JIRA: https://folio-org.atlassian.net/browse/RANCHER-1531

RANCHER-1531 Enable notifications about CI QG pipeline failures due to provision failure and skips

---

src/org/folio/eureka/EurekaImage.groovy

**Testing was done in: https://jenkins-aws.indexdata.com/job/folio-org/job/mgr-applications/job/RANCHER-1350-prerequisite/26/console**

RANCHER-1350 prerequisite

---

src/org/folio/eureka/EurekaImage.groovy

RANCHER-1361 updatePL method final | PART 1 to be merged into master branch

---

resources/helm/testing.yaml

https://folio-org.atlassian.net/browse/RANCHER-1538 "Update mod-fqm-manager resource configuration"
See #549

Fix 2800i to 2800Mi

---

pipelines/folioRancher/folioDevOpsTools/manageAwsEksCluster/createAwsEksCluster/Jenkinsfile
pipelines/folioRancher/folioQualityGates/Jenkinsfile
resources/helm/development.yaml
resources/helm/testing.yaml
terraform/rancher/cluster/catalogs.tf
terraform/rancher/cluster/eks.tf
terraform/rancher/cluster/helm.tf
terraform/rancher/cluster/kubecost.tf
terraform/rancher/cluster/logging.tf
terraform/rancher/cluster/main.tf
terraform/rancher/cluster/monitoring.tf
terraform/rancher/cluster/sorry-cypress.tf
terraform/rancher/cluster/variables.tf
terraform/rancher/project/kafka.tf
terraform/rancher/project/locals.tf
terraform/rancher/project/main.tf
terraform/rancher/project/minio.tf
terraform/rancher/project/opensearch.tf
terraform/rancher/project/postgresql.tf
vars/folioHelm.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1532

RANCHER-1532 Split folio-testing AWS EKS cluster into different NodeGroups to avoid conflicts in testing

---

resources/helm/development.yaml
resources/helm/testing.yaml

Adjust mod-fqm-manager memory values for rancher dev/testing environments

Adjust mod-fqm-manager memory

---

src/org/folio/Constants.groovy
src/org/folio/models/LdpConfig.groovy
src/org/folio/models/OkapiConfig.groovy
src/org/folio/rest_v2/Configurations.groovy
src/org/folio/rest_v2/Main.groovy
vars/folioHelm.groovy
vars/folioHelmFlow.groovy
vars/folioNamespaceCreate.groovy
vars/folioNamespaceDelete.groovy

JIRA: https://folio-org.atlassian.net/browse/FAT-4684

FAT-4684 mod-ldp configuration of ldp DB

---

src/org/folio/eureka/EurekaImage.groovy

https://jenkins-aws.indexdata.com/job/folio-org/job/folio-module-sidecar/job/dockerImageBuild/6/console
**Result: https://github.com/folio-org/platform-complete/blob/snapshot/eureka-platform.json#L28**

RANCHER-1576 Unique image identifier

---

pipelines/folioRancher/folioDevTools/tenantManagement/createConsortia/Jenkinsfile
pipelines/folioRancher/folioDevTools/uiManagement/deployUI/Jenkinsfile

**TESTED IN https://jenkins-aws.indexdata.com/job/folioRancher/job/folioDevTools/job/uiManagement/job/deployUI/154/console**

RANCHER-1569 for UI mgmt pipeline

---

pipelines/folioRancher/folioDevTools/tenantManagement/createTenant/Jenkinsfile
pipelines/folioRancher/folioDevTools/uiManagement/buildUI/Jenkinsfile
pipelines/folioRancher/folioDevTools/uiManagement/deployUI/Jenkinsfile
src/org/folio/models/Index.groovy
src/org/folio/models/OkapiTenant.groovy
src/org/folio/rest_v2/Main.groovy
src/org/folio/rest_v2/Okapi.groovy
vars/folioDefault.groovy
vars/folioNamespaceCreate.groovy

Add authority indexation during env provisioning
Jira: https://folio-org.atlassian.net/browse/RANCHER-1486

RANCHER-1486

---

resources/helm/development.yaml
resources/helm/testing.yaml
terraform/rancher/project/locals.tf

JIRA: https://folio-org.atlassian.net/browse/RANCHER-1561

RANCHER-1561 Update configs of S3/Minio for mod-marc-migrations and mod-entities-links module

---

pipelines/folioRancher/folioTestingTools/runCypressTests/Jenkinsfile
vars/folioCypressFlow.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1487

RANCHER-1487 Add AQA sanity suite as a step to runCypressTests pipeline

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createDailySnapshotECS/Jenkinsfile
src/org/folio/rest_v2/Main.groovy
vars/folioDefault.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1589

RANCHER-1589 Add location index with prepopulated data on Rancher based envs

---

vars/folioCypressFlow.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1609

RANCHER-1609 The running tests in sequential on different environments is not working

---

resources/helm/performance.yaml
resources/helm/testing.yaml
vars/folioHelm.groovy
vars/folioTools.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1625

RANCHER-1625 Auth token fetch error

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml
src/org/folio/rest_v2/Main.groovy
src/org/folio/utilities/Tools.groovy
vars/folioNamespaceCreate.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1623

RANCHER-1623 CI QualityGates piplene fails with error for okapi

---

resources/edge/config.yaml

Jira: https://folio-org.atlassian.net/browse/RANCHER-1599

RANCHER-1599 Karate run support for test tenant in edge-patron ephemeral properties

---

.gitignore
pipelines/folioRancher/folioQualityGates/Jenkinsfile
src/org/folio/models/ChangelogEntry.groovy
src/org/folio/models/FolioModule.groovy
src/org/folio/utilities/GitHubClient.groovy
vars/folioChangeLog.groovy
vars/folioCypressFlow.groovy
vars/folioHashCommitCheck.groovy
vars/folioKarateFlow.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1596

RANCHER-1596 Create folioCollectChangelog() function and integrate into CIQualityGate pipeline

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

Jira: https://folio-org.atlassian.net/browse/RANCHER-1642

RANCHER-1642 Add kafka intgration for mod-tlr

---

pipelines/folioRancher/folioTestingTools/runCypressTests/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-1635

RANCHER-1635 Enable Report Portal integration for runCypressTests Pipeline

---

pipelines/folioRancher/folioQualityGates/Jenkinsfile
vars/folioChangeLog.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1661

RANCHER-1661 Build change log text should be available with build pipeline

---

resources/helm/performance.yaml

Jira: https://folio-org.atlassian.net/browse/RANCHER-1641

RANCHER-1641 Add persistent storage for mod-data-export performance config

---

pipelines/folioRancher/folioQualityGates/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-1694

RANCHER-1694 CI QG Pipeline set sha to null if build triggered with 'SKIP_CHECK'

---

resources/helm/performance.yaml
resources/helm/testing.yaml

Jira: Implement JMX integration for Helm charts

RANCHER-1726 mplement JMX integration for Helm charts

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

Jira: https://folio-org.atlassian.net/browse/RANCHER-1691

RANCHER-1691 CI CG pipeline is unstable

---

pipelines/folioRancher/folioDevTools/moduleDeployment/deployModuleFromFeatureBranch/Jenkinsfile
pipelines/folioRancher/folioDevTools/moduleDeployment/deployModulesFromJson/Jenkinsfile
pipelines/folioRancher/folioDevTools/moduleDeployment/installModulesFromJson/Jenkinsfile
src/org/folio/models/ChangelogEntry.groovy
src/org/folio/models/FolioInstallJson.groovy
src/org/folio/models/Modules.groovy
src/org/folio/models/module/FolioModule.groovy
src/org/folio/models/module/ModuleType.groovy
src/org/folio/models/module/VersionType.groovy
vars/folioChangeLog.groovy
vars/folioHelm.groovy
vars/folioVersions.groovy
vars/kubectl.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1633

RANCHER-1633 Create a Jenkins job for new modules installation for existing environment

---

pipelines/folioRancher/folioScheduledTesting/runNightlyCypressTests/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-1571

RANCHER-1571 Change schedule to not conflict

---

pipelines/folioRancher/folioScheduledTesting/runNightlyCypressEurekaTests/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-1570
Jira: https://folio-org.atlassian.net/browse/RANCHER-1571
Job: https://jenkins-aws.indexdata.com/job/folioRancher/job/folioScheduledTesting/job/runNightlyCypressEurekaTests/

RANCHER-1570 & RANCHER-1571

---

pipelines/folioRancher/folioNamespaceTools/managePods/Jenkinsfile

Reverting changes, because request was until 10 Oct

Revert "Remove spitfire env from managepods"

---

pipelines/folioRancher/folioQualityGates/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/karateTestsScheduledPipeline.groovy
pipelines/folioRancher/folioScheduledTesting/runNightlyCypressTests/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/runNightlyKarateTests/Jenkinsfile
terraform/rancher/project/variables.tf
vars/folioStringScripts.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1825

RANCHER-1825 Switch default postgresql version to 16

---

resources/helm/testing.yaml

It has been successfully tested here:
https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/Eureka/job/createNamespaceFromBranch-Eureka-1791/6/console

Rancher 1791. Module autoscaling has been activated on Eureka platform.

---

src/org/folio/rest_v2/Main.groovy
src/org/folio/rest_v2/Okapi.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1833

RANCHER-1833 Okapi-based environment provisioning fails due to index braking changes

---

resources/helm/development.yaml
terraform/rancher/project/opensearch.tf
terraform/rancher/project/postgresql.tf
terraform/rancher/project/variables.tf

Jira: https://folio-org.atlassian.net/browse/RANCHER-1842

RANCHER-1842 Optimise development config

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
pipelines/folioRancher/folioQualityGates/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/karateTestsScheduledPipeline.groovy
pipelines/folioRancher/folioScheduledTesting/runNightlyCypressBugfestTests/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/runNightlyCypressTests/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/runNightlyKarateTests/Jenkinsfile
pipelines/folioRancher/folioTestingTools/folioDataMigrationExecutionTime/Jenkinsfile
pipelines/folioRancher/folioTestingTools/runCypressTests/Jenkinsfile
src/org/folio/models/parameters/CreateNamespaceParameters.groovy
src/org/folio/models/parameters/CypressTestsParameters.groovy
vars/folioCypress.groovy
vars/folioCypressFlow.groovy
vars/folioParameters.groovy
vars/folioTriggerJob.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1624

RANCHER-1624 Add cypress sanity check as a post stage for createNamespaceFromBranch job

---

pipelines/folioRancher/folioDevTools/moduleDeployment/deployModuleFromFeatureBranch/Jenkinsfile
vars/folioDeployFlow.groovy

RANCHER-1827

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createDailySnapshotEureka/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/runNightlyCypressEurekaTests/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-1862

RANCHER-1862 Adjust schedule for nightly tests on cypress-eureka env

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromRdsSnapshot/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-1861

RANCHER-1861 Temporary fixate db.r6g.xlarge shape for folio-testing-sprint and folio-etesting-sprint environments

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml
terraform/rancher/project/locals.tf

Jira: https://folio-org.atlassian.net/browse/RANCHER-1836

RANCHER-1836 Create helm configuration for mod-linked-data

---

pipelines/folioRancher/folioNamespaceTools/managePods/Jenkinsfile

Quick fix for EUREKA based envs.

managePods-Eureka keycloak handler inclusion

---

pipelines/folioRancher/folioTestingTools/folioDataMigrationExecutionTime/Jenkinsfile
resources/dataMigration/get-logs-ES.json.template
terraform/rancher/cluster/logging.tf
vars/folioexecuteDataMigrationUtils.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1869

RANCHER-1869 folioDataMigrationExecutionTime job fails due to Job not found error

---

vars/folioHelm.groovy

Proof:
https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/VasylA/job/createNamespaceFromBranch-Eureka-1793-fqm/66/console

RANCHER-1793. Some workarounds for mod-inn-reach and mod-fqm have been removed

---

pipelines/folioRancher/folioDevTools/moduleDeployment/deployModuleFromFeatureBranch/Jenkinsfile
pipelines/folioRancher/folioDevTools/moduleDeployment/deployModulesFromJson/Jenkinsfile
pipelines/folioRancher/folioDevTools/moduleDeployment/installModulesFromJson/Jenkinsfile
pipelines/folioRancher/folioDevTools/tenantManagement/createConsortia/Jenkinsfile
pipelines/folioRancher/folioDevTools/uiManagement/buildUI/Jenkinsfile
pipelines/folioRancher/folioDevTools/uiManagement/deployUI/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createDailySnapshotECS/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromRdsSnapshot/Jenkinsfile
resources/folio-extensions/consortia.json
resources/folio-extensions/linked-data.json
resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml
src/org/folio/models/FolioInstallJson.groovy
src/org/folio/models/OkapiTenant.groovy
src/org/folio/models/OkapiTenantConsortia.groovy
src/org/folio/models/RancherNamespace.groovy
src/org/folio/models/module/FolioModule.groovy
src/org/folio/models/parameters/CreateNamespaceParameters.groovy
src/org/folio/rest_v2/Edge.groovy
src/org/folio/utilities/Logger.groovy
vars/folioDeployFlow.groovy
vars/folioEdge.groovy
vars/folioHelm.groovy
vars/folioNamespaceCreate.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1837

RANCHER-1837 Create logic to install mod-linked-data and ui-ld-folio-wrapper on okapi-based environment

---

pipelines/folioRancher/folioQualityGates/Jenkinsfile
src/org/folio/models/parameters/CreateNamespaceParameters.groovy
vars/folioTriggerJob.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1840

RANCHER-1840 Enable linked-data-integration for sprint and ci-qg environments

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

Related Jira Ticket:
[RANCHER-1907: Add kafka support for mod-invoice-storage, mod-organizations-storage](https://folio-org.atlassian.net/browse/RANCHER-1907)

RANCHER-1907: add integration with Kafka

---

pipelines/folioRancher/folioNamespaceTools/managePods/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-1910

RANCHER-1910 Provision okapi-based citation environment and add it to start-stop schedule

---

resources/helm/performance.yaml

Fix Kafka configuration block is absent

RANCHER-1907: add Kafka configuration block

---

resources/edge/config.yaml
resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

Jira: https://folio-org.atlassian.net/browse/RANCHER-1915

RANCHER-1915 Add helm end ephemeral-properties config for edge-erm module

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

Jira: https://folio-org.atlassian.net/browse/RANCHER-1920

RANCHER-1920 mod-login-saml fails on CI CG pipelines

---

pipelines/folioRancher/folioNamespaceTools/managePods/Jenkinsfile

Stop thunderjet-2nd environment at the end of work day

Stop thunderjet-2nd environment at the end of workday

---

vars/folioDeployFlow.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1924

RANCHER-1924 sip2 test tool not working after recreating Volaris 1 Rancher

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/deleteNamespace/Jenkinsfile
vars/folioHelm.groovy
vars/folioNamespaceDelete.groovy

RANCHER-1885 proper resources removal approach

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

Related Jira ticket:
[RANCHER-1875: Help setting up mod-camunda and mod-workflow to interact with Kafka in Aggies Rancher](https://folio-org.atlassian.net/browse/RANCHER-1875)

RANCHER-1875: setting up mod-camunda and mod-workflow to interact with Kafka

---

pipelines/folioRancher/folioDevTools/moduleDeployment/deploySidecarFromFeatureBranch/Jenkinsfile

Related Jira Ticket:
[RANCHER-1894: Create new pipeline updateSidecarFromFeatureBranch](https://folio-org.atlassian.net/browse/RANCHER-1894)

RANCHER-1894: Create new pipeline updateSidecarFromFeatureBranch

---

pipelines/folioRancher/folioEureka/buildUI/Jenkinsfile
src/org/folio/rest/GitHubUtility.groovy
src/org/folio/rest_v2/eureka/Eureka.groovy
src/org/folio/rest_v2/eureka/kong/Tenants.groovy
vars/folioNamespaceCreateEureka.groovy
vars/folioUI.groovy
vars/uiBuild.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1838
Tests:
- [createNamespaceFromBranch-Eureka-dev](https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/OleksandrH/job/createNamespaceFromBranch-Eureka-dev/10/console)
- [uiBuild-Eureka-dev](https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/OleksandrH/job/uiBuild-Eureka-dev/3/console)

RANCHER-1838 Create logic to install mod-linked-data and ui-ld-folio-wrapper on eureka-based environment

---

resources/helm/development.yaml
resources/helm/testing.yaml

RANCHER-1941: Create and set 2 env varfor (e)testing and (e)dev for linked-data module

RANCHER-1941

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createDailySnapshotECS/Jenkinsfile
vars/kubectl.groovy
vars/psqlDumpMethods.groovy

- Fixed pipeline issues
- Created the new db dump Ramsons release
- Created the new pg_restore image with the PostgreSQL 16.6 version
- Fixed reset password URL

Rancher-1943 fix daily ecs snapshot pipeline

---

pipelines/folioRancher/folioNamespaceTools/managePods/Jenkinsfile
src/org/folio/Constants.groovy
vars/kubectl.groovy
vars/managePods.groovy

**TESTED IN: https://jenkins-aws.indexdata.com/view/KitFox/job/folioRancher/job/tmpFolderForDraftPipelines/job/EldiiarD/job/managePodsV2/**
**Key differences: **
1. One execution per cluster instead of many for each of namespaces in cron schedule
2. Single cron
3. Ability to permanently exclude namespace by adding into list of RANCHER_KNOWN_NAMESPACES
4. Env exclusion ONLY FOR UPCOMING NIGHT no more no less
5. This approach is fully opened for future optimization
6. All logic moved to dedicated shared lib
7. All even with custom name envs will be stopped by this updated version

RANCHER-1983 Cost optimization and management overhead minimize in managePods pipeline

---

vars/folioHelm.groovy
vars/kubectl.groovy

Embedded kubectl function with small overhead in overall deployment and check status flows.

.RANCHER-1996 simple function to delete Evicted pods

---

vars/folioNamespaceDelete.groovy

1. helm releases uninstall
2. OS indices delete
3. Kafka topics delete

RANCHER-1891-v2 proper clean up process

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml
terraform/rancher/project/locals.tf

Jira: https://folio-org.atlassian.net/browse/RANCHER-2064

RANCHER-2064 Enabling system user on rancher environments

---

pipelines/folioRancher/folioScheduledTesting/runNightlyCypressEurekaTests/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-2082

RANCHER-2082 Update runNightlyCypressEurekaTests pipeline to use "eureka" autotest branch

---

src/org/folio/models/OkapiTenant.groovy
src/org/folio/models/OkapiTenantConsortia.groovy
src/org/folio/models/module/FolioModule.groovy
src/org/folio/rest_v2/Main.groovy
src/org/folio/utilities/Logger.groovy
src/org/folio/utilities/RestClient.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-2053

RANCHER-2053 Rewrite RestClient class to use cURL instead of HttpURLConnection

---

src/org/folio/utilities/RestClient.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-2094

RANCHER-2094 RestClient performance/speed degradation on short requests

---

src/org/folio/rest_v2/Okapi.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-2096

RANCHER-2096 Optimise main.refreshServicesDiscovery() function

---

build.gradle
gradle.properties
scripts/docker/jenkinsAgent/Dockerfile
scripts/docker/jenkinsAgent/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-2118

RANCHER-2118 Fix Jenkins agent image

---

terraform/jenkins/modules/jenkins/scripts/user_data.sh
terraform/rancher/cluster/versions.tf
terraform/rancher/project/versions.tf
terraform/rancher/rancher_server/versions.tf
terraform/shared/msk/versions.tf
terraform/shared/network/versions.tf
terraform/shared/opensearch/versions.tf

Jira: https://folio-org.atlassian.net/browse/RANCHER-2119

RANCHER-2119 Update terraform provider version to >=1.6.1

---

src/org/folio/Constants.groovy
src/org/folio/utilities/GitHubClient.groovy
vars/folioNamespaceCreate.groovy
vars/folioNamespaceDelete.groovy
vars/folioStringScripts.groovy
vars/folioVersions.groovy
vars/jobsParameters.groovy
vars/ldpSettings.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-2120

RANCHER-2120 Move and update Jenkins credentials

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
src/org/folio/rest_v2/eureka/Eureka.groovy
src/org/folio/rest_v2/eureka/kong/Configurations.groovy

kb-credentials enabling FINAL PART

---

pipelines/folioRancher/folioDevTools/uiManagement/buildAndDeployUI/Jenkinsfile
src/org/folio/Constants.groovy
src/org/folio/jenkins/PodTemplates.groovy
vars/folioKaniko.groovy
vars/folioParameters.groovy
vars/folioUI.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1398

RANCHER-1398 Adjust uiManagement/buildAndDeployUI pipeline

---

pipelines/folioRancher/folioDevOpsTools/manageAwsEksCluster/createAwsEksCluster/Jenkinsfile
pipelines/folioRancher/folioDevOpsTools/manageAwsEksCluster/deleteAwsEksCluster/Jenkinsfile
src/org/folio/Constants.groovy
terraform/rancher/cluster/eks.tf
terraform/rancher/cluster/variables.tf
vars/folioTerraform.groovy
vars/folioTerraformFlow.groovy

Jira:
https://folio-org.atlassian.net/browse/RANCHER-1390 
https://folio-org.atlassian.net/browse/RANCHER-1391

RANCHER-1390 and RANCHER-1391 Adjust manageAwsEksCluster/createAwsEksCluster and deleteAwsEksCluster pipeline

---

src/org/folio/jenkins/PodTemplates.groovy
terraform/jenkins/README.md
terraform/jenkins/jenkins-agents.md

Jira: https://folio-org.atlassian.net/browse/RANCHER-1370

RANCHER-1370 Create folio-jenkins-agents eks cluster for hosting build agents and connect to Jenkins

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
src/org/folio/rest_v2/Constants.groovy

Env were successfully [buld](https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/masiuk/job/2162/11/)

RANCHER-2162: Add bulk-edit and oai-pmh apps

---

pipelines/folioRancher/folioDevTools/uiManagement/buildAndDeployUI/Jenkinsfile
pipelines/folioRancher/folioEureka/buildUI/Jenkinsfile
vars/folioHelm.groovy
vars/folioUI.groovy

RANCHER-2182 UIs FailOver DNS records implementation

---

pipelines/folioRancher/folioEureka/buildUI/Jenkinsfile
vars/folioUI.groovy

RANCHER-2196 Additional option configuration

---

pipelines/folioRancher/folioScheduledTesting/runNightlyKarateEurekaTests/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-2200

RANCHER-2200 Add environment variables to folio-etesting-karate-eureka

---

terraform/jenkins/agents_efs/README.md
terraform/jenkins/agents_efs/main.tf
terraform/jenkins/agents_efs/modules/efs_cache/README.md
terraform/jenkins/agents_efs/modules/efs_cache/k8s_pv_pvc.tf
terraform/jenkins/agents_efs/modules/efs_cache/main.tf
terraform/jenkins/agents_efs/modules/efs_cache/outputs.tf
terraform/jenkins/agents_efs/modules/efs_cache/variables.tf
terraform/jenkins/agents_efs/modules/efs_cache/versions.tf
terraform/jenkins/agents_efs/outputs.tf
terraform/jenkins/agents_efs/provider.tf
terraform/jenkins/agents_efs/terraform.tf
terraform/jenkins/agents_efs/variables.tf
terraform/jenkins/agents_efs/versions.tf
terraform/jenkins/modules/jenkins/variables.tf
terraform/rancher/cluster/eks.tf
terraform/rancher/cluster/iam.tf

Jira: https://folio-org.atlassian.net/browse/RANCHER-2123

RANCHER-2123 Create a volume that could be attached to Jenkins agent container for node_modules caching

---

pipelines/folioRancher/folioTestingTools/runCypressTests/Jenkinsfile
src/org/folio/Constants.groovy
src/org/folio/jenkins/PodTemplates.groovy
vars/folioCypress.groovy
vars/folioCypressFlow.groovy
vars/folioParameters.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1412

RANCHER-1412 Adjust folioTestingTools/runCypressTests pipeline

---

pipelines/folioRancher/folioQualityGates/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/runNightlyKarateTests/Jenkinsfile
pipelines/folioRancher/folioTestingTools/runKarateTests/Jenkinsfile
src/org/folio/Constants.groovy
src/org/folio/jenkins/PodTemplates.groovy
src/org/folio/models/parameters/KarateTestsParameters.groovy
vars/folioGatlingFlow.groovy
vars/folioKarateFlow.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1413

RANCHER-1413 Adjust folioTestingTools/runKarateTests pipeline

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
terraform/rancher/project/opensearch.tf
terraform/shared/opensearch/opensearch.tf
terraform/shared/opensearch/variables.tf

Simple and reliable k8s job, which does work as it should be.

RANCHER-2189 Request implementation via TF code and automation.

---

pipelines/folioRancher/folioScheduledTesting/runNightlyCypressTests/Jenkinsfile
pipelines/folioRancher/folioTestingTools/runCypressTests/Jenkinsfile
src/org/folio/Constants.groovy
src/org/folio/models/parameters/CreateNamespaceParameters.groovy
src/org/folio/models/parameters/CypressTestsParameters.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1410

RANCHER-1410 Adjust folioScheduledTesting/runNightlyCypressTests pipeline

---

pipelines/folioRancher/folioScheduledTesting/runNightlyCypressBugfestTests/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-1411

RANCHER-1411 Adjust folioScheduledTesting/runNightlyCypressBugfestTests pipeline

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/deleteNamespace/Jenkinsfile
pipelines/folioRancher/folioQualityGates/Jenkinsfile
terraform/jenkins/modules/jenkins/scripts/user_data.sh
vars/folioTriggerJob.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-1409
P.S. Failed on slack stage, due to channels/org renaming

RANCHER-1409 Adjust folioQualityGates/folioCiQualityGates pipeline

---

pipelines/folioRancher/folioTestingTools/runGatlingTests/Jenkinsfile
vars/folioGatlingFlow.groovy

Jira: https://folio-org.atlassian.net/browse/RANCHER-2225

RANCHER-2225 Adjust folioTestingTools/runGatlingTests pipeline

---

terraform/rancher/project/opensearch.tf

RANCHER-2222 increase open search shards master

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromRdsSnapshot/Jenkinsfile

successful build
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Masiuk/job/RANCHER-1405/13/

Rancher-1405: Adjust createNamespaceFromRdsSnapshot pipeline

---

pipelines/folioRancher/folioQualityGates/Jenkinsfile
pipelines/folioRancher/folioScheduledTesting/runNightlyKarateEurekaTests/Jenkinsfile

**TESTED IN: https://jenkins-aws.indexdata.com/view/KitFox/job/folioRancher/job/folioQualityGates/job/folioCiQualityGates/1440/console**

RANCHER-2264 && RANCHER-2265 PR to master

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespace/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromRdsSnapshot/Jenkinsfile
pipelines/folioRancher/folioNamespaceTools/manageNamespace/deleteNamespace/Jenkinsfile
src/org/folio/Constants.groovy
vars/folioCommon.groovy

The result should be something like this
Ticket ref: https://folio-org.atlassian.net/browse/RANCHER-2186
Job examples:
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Arsenator/job/createNamespaceFromBranch-restrict/
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Arsenator/job/deleteNamespace-restrict/

Rancher 2186

---

pipelines/folioRancher/folioScheduledProvisioning/updateSprintTestingEureka/Jenkinsfile
vars/folioTriggerJob.groovy

Jira REF: https://folio-org.atlassian.net/browse/RANCHER-2299
RANCHER-2299

RANCHER-2299 add sprint update cron

---

pipelines/folioRancher/folioDevTools/moduleDeployment/deployModule/Jenkinsfile
pipelines/folioRancher/folioDevTools/moduleDeployment/deployModuleFromFeatureBranchEureka/Jenkinsfile
src/org/folio/models/EurekaNamespace.groovy
src/org/folio/models/EurekaTenant.groovy
src/org/folio/models/EurekaTenantConsortia.groovy
src/org/folio/models/FolioInstallJson.groovy
src/org/folio/models/OkapiTenant.groovy
src/org/folio/models/application/Application.groovy
src/org/folio/models/application/ApplicationList.groovy
src/org/folio/rest_v2/eureka/Eureka.groovy
src/org/folio/rest_v2/eureka/kong/Applications.groovy
src/org/folio/rest_v2/eureka/kong/Consortia.groovy
src/org/folio/rest_v2/eureka/kong/Permissions.groovy
src/org/folio/rest_v2/eureka/kong/TenantConsortiaConfiguration.groovy
src/org/folio/rest_v2/eureka/kong/Tenants.groovy
vars/dataMigrationReport.groovy
vars/folioNamespaceCreateEureka.groovy

Tested:
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2248-test/2/console
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2248-test/2/allure/
https://jenkins.ci.folio.org/job/folioDevTools/job/moduleDeployment/job/deployModuleFromFeatureBranchEureka/1525/console

Rancher 2248 to rancher 2236

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

Tested:
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2180-test/4/console
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2304-test/4/allure/

RANCHER-2180. Add KC_INTEGRATION_ENABLED and SECURITY_ENABLED to mgr-* module config

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml

Tested:
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2180-test/4/console
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2304-test/4/allure/

RANCHER-2180-master. Add KC_INTEGRATION_ENABLED and SECURITY_ENABLED to mgr-* module config

---

src/org/folio/models/application/ApplicationList.groovy
vars/dataMigrationReport.groovy
vars/folioNamespaceCreateEureka.groovy

Tested:
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2313-test/3/console
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2313-test/5/console

RANCHER-2313. Utilize application module list instead of install.json origin list

---

src/org/folio/rest_v2/Constants.groovy
vars/folioEurekaAppGenerator.groovy
vars/folioKarateFlow.groovy

Tested:
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2304-test/8/console

RANCHER-2304. Add "app-reporting" application

---

src/org/folio/rest_v2/Constants.groovy
vars/folioEurekaAppGenerator.groovy

Tested:
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2304-test/8/console

RANCHER-2304-master. Add "app-reporting" application

---

src/org/folio/models/application/ApplicationList.groovy
vars/dataMigrationReport.groovy
vars/folioNamespaceCreateEureka.groovy

Tested:
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2313-test/3/console
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2313-test/5/console

RANCHER-2313-master. Utilize application module list instead of install.json origin list

---

pipelines/folioRancher/folioScheduledProvisioning/updateSprintTestingEureka/Jenkinsfile

Tested:
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/updateSprintTestingEureka-2351/

RANCHER-2351. Add recreation flow and recreation CRON for the sprint testing env

---

resources/helm/development.yaml

Issue demo:
https://github.com/user-attachments/assets/9f8920be-106f-4276-b575-f866b46c8ee3

RANCHER-2387. Fine-tuning development-like env memory setting for mod-settings

---

src/org/folio/rest_v2/Constants.groovy

…ies on app-acquisitions and platform apps

RANCHER-2403. Add app-finc to Jenkins pipelines.

---

src/org/folio/models/EurekaTenant.groovy
src/org/folio/rest_v2/eureka/Eureka.groovy
src/org/folio/rest_v2/eureka/Keycloak.groovy
src/org/folio/rest_v2/eureka/Kong.groovy
vars/dataMigrationReport.groovy
vars/folioNamespaceCreateEureka.groovy

Tested:
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/createNamespaceFromBranch-2414/31/console
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/updateTimers-2414/

RANCHER-2424. Introduce the tenant login process with user credentials into the pipelines.

---

pipelines/folioRancher/folioDevTools/moduleDeployment/deployModuleFromFeatureBranchEureka/Jenkinsfile

Source Jira ticket: https://folio-org.atlassian.net/browse/RANCHER-2496
Testing runs: https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Duishenaliev/job/deployModuleFromFeatureBranchEureka-Eldiiar/15/console

RANCHER-2496 Additional option for Deploying Modules from feature branches

---

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile
src/org/folio/models/EurekaNamespace.groovy
src/org/folio/models/RancherNamespace.groovy
src/org/folio/models/parameters/CreateNamespaceParameters.groovy
src/org/folio/rest_v2/eureka/Eureka.groovy
src/org/folio/rest_v2/eureka/kong/Tenants.groovy
terraform/rancher/project/kong.tf
terraform/rancher/project/main.tf
vars/folioDefault.groovy
vars/folioNamespaceCreateEureka.groovy
vars/folioUI.groovy

DO NOT COMMENT ON SWITCHING BRANCH PLS. THIS IS TOO OBVIOUS.

RANCHER-2455 2nd Consortium implementation v1.0.0

---

pipelines/folioRancher/folioScheduledTesting/runNightlyCypressEurekaTests/Jenkinsfile

Jira: https://folio-org.atlassian.net/browse/RANCHER-2566

RANCHER-2566 Increase number of workers at runNightlyCypressEurekaTests job to 12

---

resources/helm/development.yaml
resources/helm/performance.yaml
resources/helm/testing.yaml
terraform/rancher/project/locals.tf

Jira: https://folio-org.atlassian.net/browse/RANCHER-2563

RANCHER-2563 Add new deployment config for mod-linked-data-import
