pipelines/automation/jira-tickers-move.groovy, src/org/folio/client/jira/JiraParser.groovy, src/org/folio/client/jira/model/JiraIssue.groovy
Create jenkins pipeline for change status Jira tikers depend on service version that was deployed to Bugfest 
Modify JiraIssue and JiraParser.JiraIssue  classes
Jenkins job: https://jenkins-aws.indexdata.com/job/Rancher/job/BF-419/
=> Bf 419 - Prepare script(job) to change jira statuses after BF Env update

pipelines/rancher/cluster.groovy, terraform/rancher/cluster/eks.tf
Added next lines for turn off cloudwatch log:
create_cloudwatch_log_group = false
cluster_enabled_log_types = []
And added try/catch for function terraform.tfRemoveElastic(tfWorkDir) because very often we getting errors here when destroy failed in middle because some ingress can't be deleted automaicaly
=> RANCHER-716 Switch off cloudwatch log group

vars/kubectl.groovy
see job run: https://jenkins-aws.indexdata.com/job/Rancher/job/vasili-workflow/job/fix-createconfigmap/8/console
some logs
`+ kubectl create configmap edge-inn-reach-ephemeral-properties '--namespace=rtr' '--from-file=./edge-inn-reach-ephemeral-properties' --save-config
configmap/edge-inn-reach-ephemeral-properties created
[Pipeline] sh
+ kubectl create configmap edge-rtac-ephemeral-properties '--namespace=rtr' '--from-file=./edge-rtac-ephemeral-properties' --save-config
configmap/edge-rtac-ephemeral-properties created
[Pipeline] sh
+ kubectl create configmap edge-oai-pmh-ephemeral-properties '--namespace=rtr' '--from-file=./edge-oai-pmh-ephemeral-properties' --save-config
configmap/edge-oai-pmh-ephemeral-properties created
[Pipeline] sh
+ kubectl create configmap …
=> Fix createConfigMap function

resources/helm/development.yaml
increase memory limit for the mod-pubsub module pod. was 1gb now 1.5 gb
=> increase memory limit for the mod-pubsub module pod

terraform/rancher/project/kafka.tf
limit for the kafka-ui pod memory
=> memory limit for kafka-ui

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile, terraform/rancher/project/postgresql.tf
Since we are providing env vars with creds inside, passfile option is optional, in R\W mode read replica sts deployment can't be started due to limitation on helm\tf side, i.e. diff in paths to password file:
- primary: /opt/bitnami/postgresql/secrets/postgres-password
- read: /opt/bitnami/postgresql/secrets/password 
by that metrics container can't start on read replica deployment side, causing an issue, original message helm chart can't re-use name blah blah blah, is not related to the issue, it was just our script's second attempt the perform TF apply operation.
P\S seems like that R\W in hosted variant had never been in working state.
Successful env build job: https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/createNamespaceFromBranch-1270/2/console
=> RANCHER-1270

.editorconfig, pipelines/Jenkinsfile.template, pipelines/folioRancher/folioQualityGates/Jenkinsfile, resources/helm/testing.yaml, src/org/folio/Constants.groovy, src/org/folio/models/parameters/CypressTestsParameters.groovy, src/org/folio/models/parameters/KarateTestsParameters.groovy, src/org/folio/rest/TenantConfiguration.groovy, src/org/folio/rest_v2/Configurations.groovy, src/org/folio/utilities/Tools.groovy, terraform/rancher/project/kafka.tf, terraform/rancher/project/postgresql.tf, vars/folioCypressFlow.groovy, vars/folioKarateFlow.groovy, vars/folioNamespaceCreate.groovy, vars/slackNotifications.groovy
Jira: https://folio-org.atlassian.net/browse/RANCHER-1001
=> [QG Part 2] RANCHER-1001 Integrate Karate Tests Flow with folioCiQualityGates Jenkins Pipeline

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile, pipelines/folioRancher/folioNamespaceTools/manageNamespace/deleteNamespace/Jenkinsfile, pipelines/folioRancher/folioQualityGates/Jenkinsfile, src/org/folio/models/parameters/CreateNamespaceParameters.groovy, src/org/folio/rest_v2/Configurations.groovy, src/org/folio/utilities/Tools.groovy, vars/folioEdge.groovy, vars/folioKarateFlow.groovy, vars/folioNamespaceCreate.groovy
Jira: https://folio-org.atlassian.net/browse/RANCHER-1247
=> [QG Part 3] RANCHER-1247 folioCiQualityGates failing during parallel env provisioning

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile, terraform/rancher/project/secrets.tf
**Historically all envs on our EKS cluster were created along with minio and all worked fine, current folio-testing-sprint was created with the AWS S3 to make all testing processes identical to BugFest environment.
Since "local-files" bucket not is not unique export-worker constantly reporting: Bucket already exists, failed to upload file, to mitigate this issue we are introducing a new second bucket unique name, so every env provisioned with S3 will work smoothly
P\S bucket creation IS NOT REQUIRED, module creates bucket by itself...**
=> RANCHER-1417 | mod-data-export-worker | FIX

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile, vars/folioHelm.groovy
1. Allow ECS tenants in mod-authtoken by default at any update\installs...
2. mod-data-import slicing feature override during env(ns) provisioning, if s3 == minio
Testing was completed in https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/fix-di-slicing/2/console
Thanks!
=> Additional changes for mod-data-import & mod-authtoken default values

vars/folioHelm.groovy
Related Jira Ticket:
[It is impossible to upload file wich size is 37mb in bulk-edit section on environment "folio-testing-sprint".](https://folio-org.atlassian.net/browse/RANCHER-1456)
=> RANCHER-1456: add multipart.max limits to JAVA_OPTIONS

src/org/folio/Constants.groovy, src/org/folio/eureka/EurekaImage.groovy
**Testing was done in: https://jenkins-aws.indexdata.com/job/folio-org/job/mod-consortia-keycloak/job/RANCHER-1350/5/console**
**Results:**
Link: https://eureka-registry.ci.folio.org/descriptors/mod-consortia-keycloak-1.5.0-SNAPSHOT.json
=> RANCHER-1350 Lib for publishing of Eureka application descriptor

scripts/docker/jenkinsAgent/Dockerfile, scripts/docker/jenkinsAgent/Jenkinsfile
Create a tiny base Jenkins agent docker image with tools required for common operations on Jenkins, it should include:
AWS CLI
Terraform client
Helm client
Psql and pg_dump client
Kafka client
Kubectl
Curl
Git
Java (version according to required by Jenkins for remote.jar)
Create a repository in ECR to store this Jenkins agent base image
Create a pipeline to automate build and publish operation for future upgrades
=> RANCHER-1374: Add final Jenkinsfile and Dockerfile for agent.

pipelines/Jenkinsfile.template, pipelines/folioRancher/folioDevTools/moduleDeployment/deployModuleFromFeatureBranch/Jenkinsfile, pipelines/folioRancher/folioDevTools/moduleDeployment/deployModulesFromJson/Jenkinsfile, pipelines/folioRancher/folioDevTools/moduleDeployment/installModulesFromJson/Jenkinsfile, pipelines/folioRancher/folioDevTools/uiManagement/deployUI/Jenkinsfile, pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespace/Jenkinsfile, pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile, pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromRdsSnapshot/Jenkinsfile, pipelines/folioRancher/folioNamespaceTools/manageNamespace/deleteNamespace/Jenkinsfile, src/org/folio/Constants.groovy, vars/folioCommon.groovy
Jira: https://folio-org.atlassian.net/browse/RANCHER-1792
As a result, in particular jobs that can affect folio-testing environments was added logic to request approve if job triggered by not Kitfox team member
=> RANCHER-1792 Restrict access jobs for sprint-testing environment

pipelines/folioRancher/folioDevTools/moduleDeployment/deployModuleFromFeatureBranchEureka/Jenkinsfile, resources/helm/development.yaml, src/org/folio/rest_v2/eureka/Eureka.groovy
[RANCHER-1795: Support Thunderjet with redeploying mod-consortia-keycloak from branch for UAT testing ](https://folio-org.atlassian.net/browse/RANCHER-1795)
Jenkins Pipeline for verification:
https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/Eureka/job/deployModuleFromFeatureBranchEureka/
=> RANCHER-1795: Support Thunderjet with redeploying mod-consortia-keycloak from branch for UAT testing

pipelines/folioRancher/folioNamespaceTools/manageNamespace/createNamespaceFromBranch/Jenkinsfile, resources/edge/config_eureka.yaml, src/org/folio/utilities/Tools.groovy, vars/folioEdge.groovy, vars/folioNamespaceCreateEureka.groovy
Questions:
- Why do we need to make it in this way?
- Why do we have to make Api call?
Answers:
- Currently used approach does not work & always we have to modify EP file to make edge-* modules work.
-  For Eureka based sprint testing, there was a request to make different tenants' structure, so to avoid a mess in EP file, we need to include ONLY existing tenants.
DETAILS:
- Full testing was complete in https://jenkins-aws.indexdata.com/view/KitFox/job/folioRancher/job/tmpFolderForDraftPipelines/job/EldiiarD/job/RANCHER-1770/
- Screenshots:
P\S as usual comments & suggestions are HIGLY APPRECIATED.
=> RANCHER-1770 ReWorked & GENERALIZED "ephemeralProperties" files generation

src/org/folio/Constants.groovy
Related Jira ticket:
[RANCHER-1902: Add "citation" namespace to "createNamespaceFromBranch" & "createNamespaceFromBranch-Delete" pipelines](https://folio-org.atlassian.net/browse/RANCHER-1902)
=> RANCHER-1902: add 'citation' value to EKS namespaces list

resources/helm/development.yaml, resources/helm/performance.yaml, resources/helm/testing.yaml
[RANCHER-1933: Start mod-oai-pmh module with -Dfile.encoding=UTF-8](https://folio-org.atlassian.net/browse/RANCHER-1933)
=> RANCHER-1933: extend extraJavaOpts for mod-oai-pmh

pipelines/folioRancher/folioQualityGates/Jenkinsfile, vars/folioTriggerJob.groovy
Fix: sub job Create Namespace from Branch doesn't propagate failed status to its root calling job.
=> [RANCHER-1692: Extend slack notification for FAILED status] (https://folio-org.atlassian.net/browse/RANCHER-1692)

vars/common.groovy, vars/folioEurekaAppGenerator.groovy
Tested:
https://jenkins-aws.indexdata.com/job/folioRancher/job/tmpFolderForDraftPipelines/job/VasylA/job/createNamespaceFromBranch-Eureka-2160-test/75/console
=> RANCHER-2160. Add another module descriptor source to allow utilizing custom module descriptors. Switch to correct Jenkins maven usage.

pipelines/folioRancher/folioDevTools/moduleDeployment/enableDisableSplitting/Jenkinsfile
Simple job to avoid manual activities.
=> RANCHER-2297 simple job for DI splitting mgmt final

pipelines/v2/applications/buildPush/Jenkinsfile
Tested:
https://jenkins.ci.folio.org/job/tmpFolderForDraftPipelines/job/Avramenko/job/buildAndPushApplication-2270/16/console
=> RANCHER-2270. Enable file support on the 'build&push application' pipeline

pipelines/folioRancher/folioScheduledTesting/folioQualityGates/Jenkinsfile, pipelines/folioRancher/folioTestingTools/runCypressTests/Jenkinsfile
Additional: disable sanity check by default for the runCypressTests job
=> RANCHER-2195 Increase workers number for executing e2e tests in Quality Gates pipeline

src/org/folio/rest_v2/eureka/Eureka.groovy, vars/folioEurekaAppGenerator.groovy
Fixes deployment failures when updating application descriptors for release versions (e.g., `app-edge-complete-2.1.0`) in Sunflower Rancher environments. The pipeline was failing with `NumberFormatException` because it assumed all applications have snapshot-style build numbers.
When deploying modules to Sunflower (which uses release versions), the pipeline failed with:
```
java.lang.NumberFormatException: For input string: ""
```
This occurred because:
- Release versions like `2.1.0` don't have build numbers
- The code attempted `app.build.toInteger()` on an empty string
- Added null-safe build number handling
- Safely converts build numbers: `app.build ? (app.build.toInteger() + 1).toString() : ""`
- **Snapshot versions** (`2.1.0-SNAPSHOT.123`): Increments build number (existing …
=> RANCHER-2560. Fix Application Descriptor Update for Release Versions
